name: Deploy to Beanstalk

concurrency: PRD

# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

on: workflow_dispatch
    

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - id: build
        run: npm run build:nsp

      - name: Zip files
        run: zip -r deploy.zip build

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: sw3-web
          environment_name: sw3-web
          version_label: ${{github.run_number}}
          region: us-east-2
          deployment_package: deploy.zip
